### ISSUE TITLE
Enable downloads from candidate pages

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/openFEC#2710]
Refactor API to enable downloads from candidate pages

- [ ] research current state of these endpoints
- [ ] make changes to enable downloads

### Endpoint: /candidates/totals/
- President
https://www.fec.gov/data/candidates/president/?election_year=2016&cycle=2016&election_full=true
[Example API call](https://api.open.fec.gov/v1/candidates/totals/?api_key=DEMO_KEY&sort_hide_null=true&election_year=2020&cycle=2020&election_full=true&sort=-receipts&per_page=30&page=1&office=P)
- Senate
https://www.fec.gov/data/candidates/senate/?election_year=2018&cycle=2018&election_full=true
[Example API call](https://api.open.fec.gov/v1/candidates/totals/?api_key=DEMO_KEY&sort_hide_null=true&election_year=2018&cycle=2018&election_full=true&sort=-receipts&per_page=30&page=1&office=S)
- House
https://www.fec.gov/data/candidates/house/
[Example API call](https://api.open.fec.gov/v1/candidates/totals/?api_key=DEMO_KEY&sort_hide_null=true&election_year=2018&cycle=2018&election_full=true&sort=-receipts&per_page=30&page=1&office=H)

Follow on to redis/celery training session.

**Comment by jenniferthibault** [comment]
Currently, these downloads are marked as "Coming soon" on the app interface

<img width="1156" alt="screen shot 2017-11-14 at 9 18 51 am" src="https://user-images.githubusercontent.com/11636908/32784440-dbc3325a-c91c-11e7-9486-a75923073536.png">

**Comment by PaulClark2** [comment]
I think Carlo and Lindsay hope to use the Redis/Celery training on 11/20 as a kick-off for refactoring these endpoints.

**Comment by LindsayYoung** [comment]
These views are a bit more complicated because we need to figure out which table the record is in and which schema it should use to pass the results. 

We want to make sure that the views have a method in them named `get` that returns the query. It may be easiest to refactor those views to inherit the `views.ApiResource`, but there is probably more than one way to implement it. 

Here are the relevant views

Reports view:
https://github.com/18F/openFEC/blob/34fa9465d9ec4febc601217a2bc078b4ca08b287/webservices/resources/reports.py#L100

Committee reports view:
https://github.com/18F/openFEC/blob/34fa9465d9ec4febc601217a2bc078b4ca08b287/webservices/resources/reports.py#L166

There is also an efiling reports view, I am not sure if that was in scope of the original ticket, but here is that view for reference: https://github.com/18F/openFEC/blob/develop/webservices/resources/reports.py#L246

**Comment by LindsayYoung** [comment]
for context: high priority label comes from other ticket we consolidated to this one

**Comment by lbeaufort** [comment]
PR's reviewed and merged
