### ISSUE TITLE
Implement vanilla version of Swagger 3.0 in API

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#3064]
**What we're after:**
We want to upgrade Swagger to the latest 3.0 version in order to better maintain the asset dependencies such as JS. We have decided to retain the out of the box styles in order to easier plug and play with less customization and easier upgradability.

**Comment by ccostino** [comment]
Turns out this was a bit easier than I thought it would be!  A WIP PR has been opened containing the work.

While we're looking to keep customizations down to a minimum, I think some will have to come back.  At the very least we do need to make several adjustments to fix up the interface a bit (e.g., references to the `/swagger/` URL, fixing the search functionality, etc.).

**Comment by AmyKort** [comment]
Vanilla version has already been implemented in the PR linked to this ticket

**Comment by patphongs** [comment]
Sorry I asked for this ticket to be closed prematurely. Technically the PR hasn't been merged yet, so we should not close this PR.

**Comment by patphongs** [comment]
Connected to #3065 work

**Comment by ccostino** [comment]
@patphongs and @lbeaufort, given our discussion last week of where this work could lead us and that ReDoc, while an awesome alternative, doesn't have an API console yet to try out the endpoints, should we close this issue and the associated PR for now?

/cc @apburnes

**Comment by lbeaufort** [comment]
@ccostino should I split out the exception handling into a new branch/PR? https://github.com/fecgov/openFEC/pull/3068/files#diff-7d49c60c1dd7d62ac86dc6d815d10d41

**Comment by ccostino** [comment]
@lbeaufort yes, good catch, thank you! :-)

**Comment by patphongs** [comment]
> @patphongs and @lbeaufort, given our discussion last week of where this work could lead us and that ReDoc, while an awesome alternative, doesn't have an API console yet to try out the endpoints, should we close this issue and the associated PR for now?
> 
> /cc @apburnes

@ccostino @lbeaufort @apburnes I agree that ReDoc isn't the answer given that it doesn't allow us to try out an endpoint. 

Isn't this PR still going off of just using the vanilla Swagger UI? https://github.com/fecgov/openFEC/pull/3068. I don't think it's been reconfigured with redoc yet right? If that's the case, I think we can still use this PR.

I'm in favor of closing this issue, as the implementation of the out of the box Swagger UI is already complete, it's just the additional templating that needs to happen. That is in this ticket: https://github.com/fecgov/openFEC/issues/3065. 

Thoughts?

**Comment by ccostino** [comment]
Ah, @patphongs my question in closing this issue is based on the discussion we had after checking in progress of the work.  @apburnes made great strides in learning more about what would be involved in getting Swagger UI in shape for us and it's a lot of extra work and customization that would likely put us on a path right back to where we are now.  Plus there are some of the vulnerabilities that were found, yes.

ReDoc offers much more flexibility but you're right, it doesn't have the API console functionality just yet (though it seems to be actively in development based on the activity in the repo), so it's not a choice for now.

When I was asking about closing this, I also meant stopping work and closing the PR as well.  We could come back to this at a later point to try and address, and hopefully ReDoc will be a viable option at that point, or we could continue investigating other alternatives.

Does this make sense?

**Comment by patphongs** [comment]
> Ah, @patphongs my question in closing this issue is based on the discussion we had after checking in progress of the work. @apburnes made great strides in learning more about what would be involved in getting Swagger UI in shape for us and it's a lot of extra work and customization that would likely put us on a path right back to where we are now. Plus there are some of the vulnerabilities that were found, yes.
> 
> ReDoc offers much more flexibility but you're right, it doesn't have the API console functionality just yet (though it seems to be actively in development based on the activity in the repo), so it's not a choice for now.
> 
> When I was asking about closing this, I also meant stopping work and closing the PR as well. We could come back to this at a later point to try and address, and hopefully ReDoc will be a viable option at that point, or we could continue investigating other alternatives.
> 
> Does this make sense?

@ccostino Thanks for clarifying in our slack convo. My take on this is that I would like to go forward with refactoring Swagger UI now. Mainly because it will be a lot more difficult for us to update as swagger UI gets more stale. I know it will be a challenge, but even implementing a version that is not “pretty” but functional and easy to upgrade is an important factor while we still have help to do it. Certainly open to discussion, even before the engineering sync so that we are on the same page. cc @apburnes

**Comment by patphongs** [comment]
Closing this PR in favor of this new issue. This includes completion criteria that we discussed today: https://github.com/fecgov/openFEC/issues/3094
