### ISSUE TITLE
Discuss baseline flyway migrations

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#3358]
**What we're after:**
To flesh out and understand whether or not we need to create new baselines for flyway migrations.

**Completion criteria:**
- [x] Schedule a meeting with DBAs and API team
- [x] Document the business rules coming out of that meeting

**Comment by patphongs** [comment]
Meeting scheduled for 9/10

**Comment by fecjjeng** [comment]
We had a meeting with Vraj, Joseph, Rohan, Helen, Laura, Priya, and Jean.  
Following is the summary of today's meeting regarding Flyway re-baseline based on Vraj's experience and opinion:
1. In general, projects does not re-baseline after initial baseline since creation of baseline is very time consuming and error prone.  In general the benefit of re-baseline does not out-weight the effort it takes.
2. If in any special situation that we decided to do the re-baseline, following is the high-level process:
- using pgdump (schema-only) to take a "snapshot" of the production database
- separate the resulted ddl file into logical pieces (for example, schemas, tables, triggers, etc) with appropriated size (to fit into github)
- run flyway rebaseline
3. Currently our migration file version is set to be Vxxxx.  In case it reach the V9999, the next one can be V10000, flyway will know it is following V9999.  The only drawback is the filesystem sorting will put V10000 before V9999.  A file name change (as had been done with PR#2818) can be used  to solve this issue, if desired (optional).

**Comment by patphongs** [comment]
Discussions on this have finished and outcome has been documented above. Closing this ticket.
