### ISSUE TITLE
Refactor materialized views and insert test data into base tables to include  F13 and F4.

### ISSUE THREAD

**Issue by pkfec** [fecgov/openFEC#3400]
Test data to support this ticket:https://github.com/fecgov/openFEC/issues/3382
- [x] Update the committee reports pac parties mv to include forms F13, F4 and F3P. ( The F3P here are filed by pac parties )
- [x] Update the committee total pac parties mv to include forms F13 and F4.
- [x] Insert test data into the base tables to include inaugural committees (Form 13 filers; committee type "X") and convention and host committees (Form 4/3X filers; committee types "X," "Y" or "N").

- [x] Update the sample_db.sql file with the scripts and the test data here: https://github.com/fecgov/openFEC/blob/develop/data/sample_db.sql

**Comment by hcaofec** [comment]
Reopen this ticket because:
we found a flaw in V109 migration.  It does not include the steps to make the drop/create MV seamless.  Because the endpoint still points to MV and if endpoint is called during the period between line 12 and 14, there will be an error.    To correct this, here is what we plan to do
1) refactor V109 by adding steps to make it seamless.  creating `mv_temp` and rename `mv_temp` to `mv`
2) before merging the new PR to DEV, delete entries of 109, 110 and 111 in flyway_schema_history table in DEV database to smooth the re-run  migration.  The reason to do this is because 109, 110 and 111 has already run in DEV database.   STG and PROD database are not affected because the latest migration there is 108.
3) merge new PR

**Comment by hcaofec** [comment]
with further discussion, we decide to keep the old PR and run headless migration instead during off-peak time before next release cut.
