### ISSUE TITLE
502 errors for datatables

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#3495]
Receiving 502 errors when trying to render particular datatable pages. We believe it may be database performance issues due to sort_nulls_last. 

Notable datatable pages that are broken:

- https://fec-dev-proxy.app.cloud.gov/data/receipts/
- https://fec-dev-proxy.app.cloud.gov/data/disbursements/
- https://fec-dev-proxy.app.cloud.gov/data/receipts/individual-contributions

**Comment by lbeaufort** [comment]
From the postgres 9.6 documentation

`The NULLS options are useful if you need to support "nulls sort low" behavior, rather than the default "nulls sort high", in queries that depend on indexes to avoid sorting steps.`

If you do not provide the NULLS LAST on the index the query planner will most likely need to sort the records before returning them which could cause a huge performance drop if the table contains enough records.

`CREATE INDEX index_name ON TABLE table_name (date DESC NULLS LAST)`

@rjayasekera  says more DB horsepower might address these performance issues

**Comment by lbeaufort** [comment]
The plan is to disable the `sort_nulls_last` argument for schedules A and B because they are such large data sets, and monitor performance for the rest of the data tables. Once we remove this strain on the database, the performance should recover.

**Comment by lbeaufort** [comment]
PR is merged: https://app.zenhub.com/workspace/o/fecgov/openfec/issues/3494
