### ISSUE TITLE
COH incorrect for election profile pages (/elections)

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3562]
Cash-on-hand(COH) is incorrect for election profile pages (/elections) - it's showing $0 for all the 2020 candidates I checked.

Front-end example: https://www.fec.gov/data/elections/president/2020/ cash shows as $0 for all candidates, but Trump for example has $35,407,503.95 COH.

API call: https://api.open.fec.gov/v1/elections/?api_key=DEMO_KEY&cycle=2020&election_full=true&office=president&per_page=0&sort_hide_null=true

**Comment by pkfec** [comment]
The `last_cash_on_hand_end_period` column in `ElectionsView` was incorrectly mapped which is why the amount went missing. Fixed the column mapping and tested the changes thoroughly in my local environment.  COH attribute value appear. Screenshot attached below.

![screen shot 2019-02-01 at 11 08 20 am](https://user-images.githubusercontent.com/11650355/52134698-2bf11f00-2612-11e9-84ac-c0b23ae49929.png)

**Comment by pkfec** [comment]
Currently working on writing a new test case for `president` office type.

**Comment by pkfec** [comment]
PR is merged. Hence closing the ticket.
