### ISSUE TITLE
Filter for single day (raw filings)

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/openFEC#3563]
**What we are after**:
Provide users with an intuitive way to search for a single day's filings. For example, I want to see all raw electronic filings received on 2/1/19. 

**Why we are after it**:
To help users find filings and reports they are looking for. 

**Current behavior**:
Entry in both date boxes:
![image](https://user-images.githubusercontent.com/11817734/52143194-d1af8880-2628-11e9-86c7-dc0a7caf7432.png)

Entry in beginning date box only:
![image](https://user-images.githubusercontent.com/11817734/52143332-2fdc6b80-2629-11e9-9000-0c2c06c99404.png)

**Desired behavior**:
Entering the same date in both date boxes should return filings received on that day. 

**Completion criteria**:
- [ ] Remove time stamp and filter by date only

**Comment by lbeaufort** [comment]
This is being caused by querying `receipt_date`, which is a timestamp field.

From Paul:
We do show the time from `timestamp` in the data table.
https://www.fec.gov/data/filings/?data_type=efiling&min_receipt_date=02%2F01%2F2019 (edited) 
It's under the receipt date

Laura: I was thinking we should keep receipt date the way it is, then bring in `real_efile.reps.filed_date` for query purposes

Paul:
I like the time being in the data table but the filter really should use `date_filed` or a truncated version of timestamp.
