### ISSUE TITLE
Exclude inactive candidates from election pages

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/openFEC#3564]
related to https://github.com/fecgov/openFEC/issues/3260

**What we are after**:
We need to exclude inactive candidates from election pages

**Why we are after it:**
We exclude inactive candidates from election pages so that we only show information about candidates that are actively seeking election or re-election. 

**Source data**: 
`disclosure.cand_inactive`

**Examples or current behavior**:
Alabama: Jones is the incumbent, and Sessions is an inactive candidate.
https://www.fec.gov/data/elections/senate/AL/2020/
![7a945434-aaf1-446a-8754-763f808815c5](https://user-images.githubusercontent.com/11817734/52156091-27e5f100-2654-11e9-83ea-388bddbe682e.jpeg)

Minnesota: Smith is the incumbent, and Franken is an inactive candidate.
https://www.fec.gov/data/elections/senate/MN/2020/
![image](https://user-images.githubusercontent.com/11817734/52147451-bb0f2e80-2634-11e9-8e60-bf3939db585f.png)

**Completion criteria**:
- [ ] modify queries/materialized views to exclude inactive candidates

**Comment by fecjjeng** [comment]
The main driver for the endpoint shown in the above example (ElectionView) is ofec_candidate_history_mv, which already has the candidate_inactive column.  The dynamic query built in ElectionView already has the condition candidate_inactive = false built in.  However, the sql statement that create ofec_candidate_history_mv need to be updated to produce correct data to exclude inactive candidate.  A migration file will be submit to correct this endpoint.

**Comment by qqss88** [comment]
Hi Jean,

I did some quick tracing on this one and I think the candidate totals  data are loaded from this api:
https://api.open.fec.gov/developers/#/candidate/get_candidate__candidate_id__totals_

related code from cms:
fec-cms/fec/data//templates/partials/elections/election-data-and-compliance-tab.jinja
fec-cms/fec/data/templates/candidates-single.jinja
fec-cms/fec/data/views.py --> get_candidate --> api_caller.load_candidate_totals

we can discuss this today.

**Comment by fecjjeng** [comment]
After fix the candidate_inactive data as described above, the elections endpoint has been fixed.  And the contribution by size/state of the candidate data won't be included since the inactive cand_id won't be passed to these two endpoint.  Tested with local CMS/API had confirm this.

Local server (point to a tmp version of the mv):
<img width="905" alt="screen shot 2019-02-27 at 7 38 35 pm" src="https://user-images.githubusercontent.com/24943130/53533155-b6b92280-3ac7-11e9-9bb5-28709f053c79.png">
<img width="890" alt="screen shot 2019-02-27 at 7 39 05 pm" src="https://user-images.githubusercontent.com/24943130/53533168-bde03080-3ac7-11e9-9d71-350e06e8d750.png">

Same parameters (2020, AL, S) run on production server:
<img width="894" alt="screen shot 2019-02-27 at 7 38 46 pm" src="https://user-images.githubusercontent.com/24943130/53533197-d94b3b80-3ac7-11e9-930f-a41789d04e29.png">
<img width="893" alt="screen shot 2019-02-27 at 7 39 39 pm" src="https://user-images.githubusercontent.com/24943130/53533206-dea88600-3ac7-11e9-96ba-184726a295ff.png">

**Comment by fecjjeng** [comment]
Tested on previous cycles also display correct information, examples runs include
(2016, HI, S)(2012, WV, S)

**Comment by fecjjeng** [comment]
There are still some MV dependency that were not handled berfore.
ofec_candidate_history_mv -> ofec_candidate_history_with_future_election_mv
ofec_candidate_history_mv -> ofec_candidate_detail_mv
  ofec_candidate_detail_mv -> ofec_candidate_election_mv

There are no actual change on the following MVs except referring to the front-end VW instead of base MVs:
ofec_candidate_history_with_future_election_mv
ofec_candidate_detail_mv
ofec_candidate_election_mv

**Comment by fecjjeng** [comment]
For the migration script:
Currently the model file is directly point to the mv itself.  Since during merge/build process, the database migration are perform BEFORE the updated software been deployed, the _tmp approach is used to minimize the the downtime.
It would be better to refer to the front-end VW in the API in order to take full benefit of the MV/VW pairing.  All these impacted MVs are fully indexed and hence their front-end VW will take advantage of these indexes.
Therefore in this ticket,  I also changed the involved model file of the impacted MVs to point to their front-end views instead of the base MVs so next time we do not need to use the _tmp approach.
@lbeaufort:
I don't recall any reason not to point to the front-end VW in API when it is appropriated,  Do you remember any disadvantage of this approach?

**Comment by lbeaufort** [comment]
@fecjjeng the `indexValidator` was causing problems with using the views because it couldn't see the indexes on the underlying tabes/MV's. I'd need to take a closer look, but if we're specifying which fields are sortable we should be able to remove the `indexValidator` when we switch to using the views.

**Comment by fecjjeng** [comment]
@lbeaufort 
Thanks for the input.  
The Elections endpoint does not specifying which fields are sortable, but since that class does not include indexValidator, I tried several different fields it all executed successfully. 
However, there are other endpoint referring the same model does include indexValidator so it failed.  
I will revert back to use the mv for this ticket to avoid over complicated this ticket un-necessarily.  We can revisit the usefulness of indexValidator later.
