### ISSUE TITLE
[HIGH] Snyk - SQL Injection - Fix by 20190327

### ISSUE THREAD

**Issue by rjayasekera** [fecgov/openFEC#3589]
**Vulnerable module:** SQLAlchemy@1.2.8

**Detailed paths:**
Introduced through: project@0.0.0 › marshmallow-sqlalchemy@0.15.0 › SQLAlchemy@1.2.8
Introduced through: project@0.0.0 › flask-sqlalchemy@2.1 › SQLAlchemy@1.2.8

**Remediation:**
Upgrade sqlalchemy to version 1.2.18 or higher.

- [ ] Confirm in the requirements file that the packages have been updated accordingly
- [ ] Confirm whether or not the child packages are compatible and whether those need to be updated as well

**Comment by pkfec** [comment]
API works fine with the new version of `SQLALchemy1.2.17`. I have thoroughly tested the endpoints and they are seems to work OK.
sqlalchemy release notes:
https://docs.sqlalchemy.org/en/latest/changelog/changelog_12.html#change-1.2.17

**Comment by pkfec** [comment]
`pytest` are failing lately due to dependency package `pathlib` which is replaced with `pathlib2`. `pathlib` is a dependency package downloaded from `open-apispec-validator`. The latest version of 
`openapi-spec-validator0.2.6` is still on `pathlib` and it's causing the `pytest` to fail locally and on circle when built without cache.

Waiting for the latest release of `openapi-spec-validator` with the `pathlib2`.

More info on` openapi-spec-validator`:
https://github.com/p1c2u/openapi-spec-validator
https://pypi.org/project/openapi-spec-validator/0.2.6/
