### ISSUE TITLE
Research options for protecting downloads endpoint

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#3630]
**What we're after:** Downloads endpoint not really intended for public (more for front-end use) but browser design makes it easily accessible. We’re not sure how to protect this endpoint. Can’t require a log in. This ticket will serve as a research ticket to explore options on how to protect this endpoint from being overburdened and bombarded with requests.

**Consider the following:**
Maybe tokenize requests, ~reduce the number of our celery workers~ (moved to https://github.com/fecgov/openfec/issues/3637), or make end point harder to ping; this is new territory for us, so it’s difficult.

**Completion criteria:**
- [ ] Research best practices or possible solutions for this issue
- [ ] Document research
- [ ] Make a recommendation on next steps

**Comment by patphongs** [comment]
Related issue #3629

**Comment by patphongs** [comment]
Moved the celery worker task to this issue: https://github.com/fecgov/openfec/issues/3637

**Comment by patphongs** [comment]
In order to rate limit the amount of download requests per IP, we need to allow restrict the downloads endpoint to only 1 download key. Then we will be able to apply rate limits to that key as desired. This will protect us from a single IP requesting too many downloads all within a short timeframe.

![Rate limit downloads](https://user-images.githubusercontent.com/12799132/54779759-5b71e000-4bee-11e9-8b11-04bffc05f858.jpg)

**Suggested follow-up tickets:**

1. Create new download key, one per environment.
2. Rate limit the new key. Each ping to check task status is considered a request. We may want to start with allowing 100 requests per hour per IP. Calculations are as follows: 100 requests / 4 average pings per request = ~25 CSV download files can be requested per hour
3. Create restrictions on the `/download/` endpoint to only allow requests from new download key
4. On the front end, add error handling messages for exceeding the request limit. Ex: "You have exceeded the maximum allowed download requests this hour".

**Comment by patphongs** [comment]
New implementation ticket has been created here: https://github.com/fecgov/openFEC/issues/3651
