### ISSUE TITLE
Add candidate ID - committee ID link for leadership PACs

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3765]
@PaulClark2 suggested we ask Debbie if the RAD reports processing branch could add the candidate ID of the associated candidate when processing Form 1's. This would allow us to link candidates and leadership PACs.

This probably shouldn't go in the candidate-committee linkage tables - we may want to create a new candidate-leadership-committee linkage table for this purpose.

Original research issue: https://github.com/fecgov/openFEC/issues/3433

- [ ] Create follow up tickets for next steps

**Comment by PaulClark2** [comment]
I'll start the conversations with Debbie and Ryan about systematically adding sponsor information based on data provided by the filer on Line 6 of Form 1.

**Comment by PaulClark2** [comment]
Good morning, Debbie and Ryan.  

Ryan, as we discussed, here’s the email more formally requesting we add leadership PAC candidate ID to the electronic filing specification of Form 1.

So that we can provide better information to the public on our website, we’d like to add leadership PAC candidate ID to the electronic filing specification of Form 1. On the website leadership PACs might be displayed in a few places, see below. The examples below are just a few thoughts Ryan and I discussed yesterday. If we move forward with this, how we display this information will go through our normal website development process, including internal approvals. 

Please let me know have concerns about this. I’m happy to meet with you to discuss this proposal.  

-Paul

In sitewide search results, https://www.fec.gov/search/?type=candidates&type=committees&type=site&query=mcconnell. Text under the committee name would describe the committee’s type and designation.
![1.png](https://images.zenhubusercontent.com/59563d2061b4ca3b0a72d03d/c582869f-be73-4072-a452-43bfd169e4e6)
 
On the ‘About this candidate” tab of candidate profile pages, https://www.fec.gov/data/candidate/S6NV00028/?tab=about-candidate. We would add a section for leadership PACs. 
![2.png](https://images.zenhubusercontent.com/59563d2061b4ca3b0a72d03d/2a51a354-bd72-4073-aee6-5c53099c6ddf)
 
On the general committee data table, https://www.fec.gov/data/committees/?designation=D. We’d like to add information about the leadership PAC’s sponsor in the data table or the details panel. 
![3.png](https://images.zenhubusercontent.com/59563d2061b4ca3b0a72d03d/fad9469a-5ea2-447e-ba02-85c306bc0345)
![4.png](https://images.zenhubusercontent.com/59563d2061b4ca3b0a72d03d/591f24ed-2f35-4251-83a6-522945a50638)

**Comment by PaulClark2** [comment]
RAD is on-board with this change.

**Comment by PaulClark2** [comment]
This does not require a form change. The request goes to RAD and Information Division. 

Changes to the electronic filing specifications generally take 90 days.
