### ISSUE TITLE
[Snyk: Med] Deserialization of Untrusted Data found in parso [due: 10/5/2019 (as of 8/5, no remediation)]

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#3894]
## Summary ##

found in `requirements-dev.txt`

```
Medium severity vulnerability found in parso
Description: Deserialization of Untrusted Data
Info: https://snyk.io/vuln/SNYK-PYTHON-PARSO-174930
Introduced through: ipython@7.5.0
From: ipython@7.5.0 > jedi@0.13.3 > parso@0.4.0
```

## Overview ##
`parso` is a Python parser that supports error recovery and round-trip parsing for different Python versions.

Affected versions of this package are vulnerable to Deserialization of Untrusted Data. A deserialization vulnerability exists in the way parso handles grammar parsing from the cache. Cache loading relies on pickle and, provided that an evil pickle can be written to a cache grammar file and that its parsing can be triggered, this flaw leads to Arbitrary Code Execution.

## Remediation ##
There is no fixed version for `parso`.

## Completion critera ##
- [ ] verify if this vulnerability is still an issue.
- [ ] resolve as needed and verify resolution

**Comment by lbeaufort** [comment]
This is no longer being flagged by Snyk, possibly because the CVE is disputed  - see an interesting discussion [here](https://github.com/davidhalter/parso/issues/75) and the CVE issue [here](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-12760).

We don't need to address this issue unless Snyk flags it again, or anything changes.
