### ISSUE TITLE
Reach out `CandidateTotalsView` API users replace full_election to election_full

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#3922]
Reference openFEC PR : [https://github.com/fecgov/openFEC/pull/3919
](https://github.com/fecgov/openFEC/pull/3919)

We recently update the endpoint: /candidate/{candidate_id}/totals/ under tag: candidate
resource file: CandidateTotalsView
The parameter **full_election** is replaced by **election_full** .

We should reach out to API users who use this endpoint.
send the notice message something like this: "Parameter full_election is replaced by election_full. Please use election_full instead."

**Comment by PaulClark2** [comment]
Email sent 8/30. 

Good morning, FEC API users.

The purpose of this email is to inform you of a parameter change within the "/candidate/{candidate_id}/totals/ " endpoint. You are being contacted because data.gov's API umbrella indicates your email address is associated with an API key that made a request to a "/candidate/" endpoint (Request: URL Path CONTAINS /v1/candidate/) sometime in the past four months.

As part of our September 10 production release we will change the "full_election" parameter of "/candidate/{candidate_id}/totals/ " endpoint to "election_full."

If you have any questions or concerns please contact the FEC at APIinfo@fec.gov.

Regards,
FEC openAPI team
