### ISSUE TITLE
Schedule A, B, and E aggregate endpoints can't filter by committee ID

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#3995]
The endpoints:
```
/schedules/schedule_a/by_size/
/schedules/schedule_a/by_state/
/schedules/schedule_a/by_zip/
/schedules/schedule_a/by_employer/
/schedules/schedule_a/by_occupation/
/schedules/schedule_b/by_recipient/
/schedules/schedule_b/by_recipient_id/
/schedules/schedule_b/by_purpose/
/schedules/schedule_e/by_candidate/
```
...should have the ability to filter by one or more committee ID (the filer ID) but they don't. In comparison, these endpoints use the same resource files as `/commitee/<commitee_ID>/schedules/schedule_a/by_state/` etc which do filter by a required committeeID parameter.

**Code for two aggregate endpoints per view**
https://github.com/fecgov/openFEC/blob/20e55b379b55baa17abd0be5f2595adfec5e390b/webservices/rest.py#L332-L350

This is pretty difficult to split out because the committee_id filter is "automagically" added by a combination of packages when it's in the URL but not otherwise. I put together a prototype of trying to split this logic out: https://github.com/fecgov/openFEC/pull/3994. I think it's pretty involved. We'll also need to fix our automated tests because if we take this approach the `url_for` may need to point to the new view.

**Completion criteria**
- [ ] Add `committee_id` as a filter_multi to these endpoints
- [ ] Make sure `committee_id` isn't added to the `/commitee/<commitee_ID>/schedules/schedule_a/by_state/` etc. endpoints

**Comment by fec-jli** [comment]
Currently, we have two sets of endpoints for schedule aggregate.
The difference is the first set of endpoints, filter by committee_ID which is mandatory parameter. don't know which sets has more advantage then other one.
1) /commitee/<commitee_ID>/schedules/schedule_x/by_xxxxxx/
2) /schedules/schedule_x/by_xxxxxx/

they share the same resource files and doc discription message.

after adding the filter by commitee_ID into /schedules/schedule_x/by_xxxxxx/
these two endpoints are the same:
/schedules/schedule_x/by_xxxxxx/?committee_id=C123456
/commitee/C123456/schedules/schedule_x/by_xxxxxx/

question 1:
most of our frontend call /schedules/schedule_x/by_xxxxxx/, except committee-single.js and candidate-single.js. we can switch them easily(modify helpers.buildUrl / path). 
Do we intend to keep using the /schedules/schedule_x/by_xxxxxx/ in our application? 
Due to outside api users may still call /commitee/<commitee_ID>/schedules/schedule_x/by_xxxxxx/, I think we need keep this one(shorter url length)?
Can we just keep one endpoint in the future?

question 2:
for the function add_aggregate_resource() in rest.py, I don't see any advantage for this. neither for static code to save code lines nor dynamic
performance increase. I am planning to remove that function.

replace with the following simple and clear codes:
api.add_resource(aggregates.ScheduleABySizeView, '/schedules/schedule_a/by_size/')
api.add_resource(aggregates.ScheduleAByStateView, '/schedules/schedule_a/by_state/')
api.add_resource(aggregates.ScheduleAByZipView, '/schedules/schedule_a/by_zip/')
api.add_resource(aggregates.ScheduleAByEmployerView, '/schedules/schedule_a/by_employer/')
api.add_resource(aggregates.ScheduleAByOccupationView, '/schedules/schedule_a/by_occupation/')


question 3:
In case, if we want to remove /commitee/<commitee_ID>/schedules/schedule_x/by_xxxxxx/ in the future. It is better to separate them now totally.

ex: create 5 new classes for scheduleA that committeID is mandatory parameter, don't mix up code with the above endpoints.
ScheduleABySizeByCommitteIDView
ScheduleAByStateByCommitteIDView
ScheduleAByZipByCommitteIDView
ScheduleAByEmployerByCommitteIDView
ScheduleAByOccupationByCommitteIDView

in this way, we can write particular doc discription for /commitee/<commitee_ID>/schedules/schedule_x/, don't need share with the above message.

**Comment by lbeaufort** [comment]
Thanks for your work on this and  thoughtful questions, @fec-jli! Here's my take:

>question 1:
>most of our frontend call **/schedules/schedule_x/by_xxxxxx/**, except committee-single.js and >candidate-single.js. we can switch them easily(modify helpers.buildUrl / path). 
>Do we intend to keep using **/schedules/schedule_x/by_xxxxxx/** in our application? 
>Due to outside api users may still call /committee/<committee_ID>/schedules/schedule_x/by_xxxxxx/, >I think we need keep this one(shorter url length)?
>Can we just keep one endpoint in the future?

Yes, it makes sense to me to only use one endpoint. Steps could be: 
1) Add [DEPRECATED] to the endpoint descriptions for the <committee_id> endpoints
2) Switch the front end to use the same endpoints. (I'm wondering how they filter the results by committee ID?)
3) Notify API users that have called the <committee_id> endpoints in the past 3 months
4) Give folks a few weeks to respond
5) Remove the old endpoints. Consider adding a validation message telling them to use the **/schedules/schedule_x/by_xxxxxx/** endpoints

>question 2:
>for the function **add_aggregate_resource()** in rest.py, I don't see any advantage for this. >neither for static code to save code lines nor dynamic performance increase. I am planning to >remove that function.
>
>Replace with the following simple and clear codes:
>api.add_resource(aggregates.ScheduleABySizeView, '/schedules/schedule_a/by_size/')
>api.add_resource(aggregates.ScheduleAByStateView, '/schedules/schedule_a/by_state/')
>api.add_resource(aggregates.ScheduleAByZipView, '/schedules/schedule_a/by_zip/')
>api.add_resource(aggregates.ScheduleAByEmployerView, '/schedules/schedule_a/by_employer/')
>api.add_resource(aggregates.ScheduleAByOccupationView, '/schedules/schedule_a/by_occupation/')
>

I agree
>question 3:
>In case, if we want to remove **/committee/<committee_ID>/schedules/schedule_x/by_xxxxxx/** in the >future. It is better to separate them now totally.
>
>ex: create 5 new classes for scheduleA that committeeID is mandatory parameter, don't mix up code >with the above endpoints.
>ScheduleABySizeByCommitteeIDView
>ScheduleAByStateByCommitteeIDView
>ScheduleAByZipByCommitteeIDView
>ScheduleAByEmployerByCommitteeIDView
>ScheduleAByOccupationByCommitteeIDView
>
>in this way, we can write particular doc description for **/committee/<committee_ID>/schedules/>schedule_x/**, don't need share with the above message.

That sounds good to me, thanks @fec-jli!
