### ISSUE TITLE
Ann Arbor missing from individual contributions search

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#4111]
### Problem
API user reports that https://www.fec.gov/data/receipts/individual-contributions/?committee_id=C00342204&contributor_city=Ann+Arbor

returns no results. I checked the db, and the following

```sql
select * from disclosure.fec_fitem_sched_a where cmte_id = 'C00342204' and contbr_st='MI' and contbr_city='Ann Arbor';
```

does return results.

### completion criteria
- [ ] Find out why Ann Arbor is not found and fix/explain

**Comment by fec-jli** [comment]
The reason is that searching by contbr_city is case sensitive.
we don't add upper() in where clause properly when we build where condition using filters.filter_multi()
The filters.xxxxx() is general function, it may affect other endpoints and other fields too. 
we need check them and make sure they build the correct **where condition sql**.
The parameter we pass in through kwargs is always upper case (like this: ANN ARBOR), that is correct.

The backend query is: (return 29 rows)
select * FROM disclosure.fec_fitem_sched_a 
LEFT OUTER JOIN ofec_committee_history_mv AS ofec_committee_history_mv_1 ON disclosure.fec_fitem_sched_a.cmte_id = ofec_committee_history_mv_1.committee_id AND disclosure.fec_fitem_sched_a.two_year_transaction_period = ofec_committee_history_mv_1.cycle 
LEFT OUTER JOIN ofec_committee_history_mv AS ofec_committee_history_mv_2 ON disclosure.fec_fitem_sched_a.clean_contbr_id = ofec_committee_history_mv_2.committee_id AND disclosure.fec_fitem_sched_a.two_year_transaction_period = ofec_committee_history_mv_2.cycle 
WHERE disclosure.fec_fitem_sched_a.is_individual = true 
AND disclosure.fec_fitem_sched_a.cmte_id IN ('C00342204') 
AND disclosure.fec_fitem_sched_a.contbr_city IN ('Ann Arbor')
ORDER BY disclosure.fec_fitem_sched_a.contb_receipt_dt DESC

**Comment by fec-jli** [comment]
After checking the python code and researching the upper case function on both python side and sql query side.

The conclusion:
1)By our existing design, the data in fec_fitem_sched_x should be all uppercase in Postgres DB.
2)Due to big data set and overhead, we don’t do func.upper(column) in filters.py when building ‘where clause condition’. It is impossible to ad upper() function because very bad performance based on big fec_fitem_sched_x tables.
3)nothing needs to change on python side.
4)will create a database issue to fix data inside fec_fitem_sched_x tables.
so close this issue. Thanks

**Comment by jason-upchurch** [comment]
nice work @fec-jli thank you for taking the time to explain this to me!
