### ISSUE TITLE
Test IE "most recent" work. Need data experts

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/openFEC#4152]
**Summary**
Testing must be completed on the current work that is ongoing on IE data. 

Testing that the current filter check box actually works in processed and raw and confirm that the methodology is there.

Testing must be complete by Friday, 1/24/2020

**Previous IE work:**
fecgov/fec-cms#3011 (Implement changes to flyout and filter panel - Raw)
fecgov/fec-cms#3370 (Implement changes to flyout and filter panel - Processed)

**Completion Criteria**
- [x] Make sure the methodology box comes up.
- [x] Check the processed toggle for independent expenditure data table.
- [x] Make sure check box filter works for current version (processed)
- [x] Make sure check box filter works for current version (raw)

**Comment by fecjjeng** [comment]
The web page address for this page is:
https://dev.fec.gov/data/independent-expenditures/?data_type=processed&most_recent=true&is_notice=true

**Comment by fecjjeng** [comment]
There is a cms issue opened for this page https://github.com/fecgov/fec-cms/issues/3533:
The IE datatable does not indicate that the data has not finished loading yet when checking and unchecking the current version filter.

**Comment by fecjjeng** [comment]
Version methodology box:
The version methodology box does come up when clicked.  However, the description in the methodology need to be updated to give a more accurate and understandable description.
A separate cms issue (Update IE methodology #3537) had been opened by @patphongs to update the version methodology.

**Comment by fecjjeng** [comment]
Check the processed toggle for independent expenditure data table.  Make sure check box filter works for current version (processed):

- For regularly scheduled reports, all records are most_recent.  Toggle the current version box will produce the same number of rows returns.

For P00001571 (s_o_ind = 'S') 2019-2020, both cases returns 3034 rows.
https://dev.fec.gov/data/independent-expenditures/?data_type=processed&is_notice=false&most_recent=true&candidate_id=P80001571&support_oppose_indicator=S
vs
https://dev.fec.gov/data/independent-expenditures/?data_type=processed&is_notice=false&candidate_id=P80001571&support_oppose_indicator=S

F3X returns 2957 rows (with and without current version box checked)
F5 returns 77 rows (with and without current version box checked)

- For 24- and 48-Hour Reports.  Toggle the current version box could produce different number of rows returns.
For P00001571 (s_o_ind = 'S') 2017-2018, check current_version box returns 733 rows, while uncheck the box returns 744 rows.  Query from database returns the same result (744 vs 733 rows):
select file_num, filing_form, s_o_cand_nm, pye_nm, s_o_ind, exp_dt, exp_amt
from ofec_sched_e_mv
where rpt_yr IN (2017, 2018) 
and is_notice = true 
and s_o_cand_id = 'P80001571'
and s_o_ind = 'S'
--and most_recent = true
order by exp_dt, exp_amt;
#######
However, when toggle with Form 3X/Form 5 check box, select either or both these two boxes will result in no rows returns.  The database query above indicated all filing_form is F24.  Form24 is not a real form type.  It is a special case for Form3X when PAC committees filing 24/48 hours notice.  Front-end will need to pass in F24 instead of F3X when F3X box is selected for 24/48 hours notice.  A fec-cms tickets had already been opened for this task (https://github.com/fecgov/fec-cms/issues/3463)

- A committees that filing several long amendment chain of 24/48 hours notice (C00662312) had also been tested:
select file_num, filing_form, s_o_cand_nm, pye_nm, s_o_ind, exp_dt, exp_amt
from ofec_sched_e_mv
where cmte_id = 'C00662312' and rpt_yr IN (2017, 2018) 
and is_notice = true 
and pye_nm like 'VARGAS%'
and s_o_ind = 'O'
--and most_recent = true
order by exp_dt, exp_amt:
https://dev.fec.gov/data/independent-expenditures/?data_type=processed&committee_id=C00662312&cycle=2018&is_notice=true&support_oppose_indicator=O&payee_name=VARGAS
vs
https://dev.fec.gov/data/independent-expenditures/?data_type=processed&committee_id=C00662312&cycle=2018&is_notice=true&most_recent=true&support_oppose_indicator=O&payee_name=VARGAS

**Comment by fecjjeng** [comment]
Make sure check box filter works for current version (raw):

A C9 committee (Form 5 filer) that filing several long amendment chain of 24/48 hours notice (C90015868) had also been tested:

select repid, so_can_name, supop, filing_form, most_recent, is_notice
from real_efile_se_f57_vw
where comid = 'C90018854'
and is_notice = true
--and most_recent = true
order by comid, exp_date, amount, most_recent, repid

uncheck current_version box returns 10 rows, while check the box returns 8 rows. Query from database returns the same result (10 vs 8 rows).

The repid returns from the above query indicated these rows are from 2 amendment chain:
{1368303}
{1361001,1369419}

check the current_version box returns the 2 rows from the latest filing of these chain (1368303, 1369419)

**Comment by fecjjeng** [comment]
The web page for both processed and raw data pass the `is_notice=true` by default

**Comment by fecjjeng** [comment]
A business logic update in that we need most_recent null values to be included with calling most_recent=true.  Currently when front end calling most_recent=true, it does not include the null (unknown) data.  An issue had been opened to deal with this update of logic.
https://github.com/fecgov/openFEC/issues/4208

**Comment by fecjjeng** [comment]
https://github.com/fecgov/openFEC/issues/4208 
    Schedule_e 'most_recent=true' logic update
https://github.com/fecgov/fec-cms/issues/3549 
    IE raw data tab only returns notice, not return regular reports
https://github.com/fecgov/fec-cms/issues/3537
    Update IE methodology
