### ISSUE TITLE
Committee profile page for C00634212 does not show totals for 2020 cycle

### ISSUE THREAD

**Issue by fecjjeng** [fecgov/openFEC#4215]
Committee profile page for C00634212 does not show totals for 2020 cycle for KATIE HILL due to the committee type change in the middle of the financial cycle 

https://www.fec.gov/data/committee/C00634212/. 
<img width="882" alt="Screen Shot 2020-02-18 at 10 07 46 AM" src="https://user-images.githubusercontent.com/24943130/74748482-92a1a480-5236-11ea-891f-ba7f3c70d708.png">

**Comment by hcaofec** [comment]
After this committee changed from House to PAC, financial summary tab is looking for F3X to display the totals.  The pac_party totals view will be refactored to look for committee type. 

A follow-up ticket will be created to focus on whether making cycle a required field.
 
From Slack summarized by Laura:
To summarize, @hcao can make the bug fix without requiring cycle because it defaults to the most recent. This isn’t great practice (secret default value, confusing results) so Helen is going to enter a follow-up ticket to make the breaking change to require cycle, but follow our deprecation policy here: https://github.com/fecgov/openFEC/wiki/Deprecation-policy
@hcao PS

**Comment by pkfec** [comment]
@hcaofec Did you create follow up ticket based on the discussion you had with the team? 
Is there any additional work that needs to happen in this ticket before closing this ticket?

**Comment by pkfec** [comment]
PR #4239 is merged. Closing this issue.

**Comment by hcaofec** [comment]
In api, there is logic to get latest cycle of the committee if no cycle is passed.  This can be considered as having default value for cycle.

A following up ticket on removing ofec_totals_pacs_parties_mv will be created.
