### ISSUE TITLE
Setting up Aurora database instance version 10.7 for testing (database creation and data loading)

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#4286]
### Summary

**What we're after:**
Aurora database (an advanced version of postgresql database on AWS) was suggested by AWS Envision team to help alleviate the slow query problem we had encountered with increasing amount of data.  The first step to migrate from our current postgresql database to Aurora database instance is to set up test Aurora database instance and load real data as the base for test out all applications that load/query data from it.

### Related issues
- #4287 
- #4288 
- #4289 
- #4290 
- #4291 

### Completion criteri
- [x] Create a Aurora version 10.7 database instance 
- [x] Create database, set up database roles/permission 
- [x] Backup data from current postgresql database and create/load databases objects and data into the new Aurora database
- [x] Create replicas for developers to connect and test

### Future work
- #4287 
- #4288 
- #4289 
- #4290 
- #4291

**Comment by fecjjeng** [comment]
From AWS console, an aurora database cluster with version 10.7 had been created.  This is the highest version supported in gov cloud and also the python package support is compatible with our current code.
A master database instance (read/write) is created.
A user generation script had been created by quering current dev database for username and permissions.  This script is used to re-create users in the current dev database in the new dev-Aurora database.
An ec2 server had been setup in gov cloud and was used to run pg_dump from the current postgres dev database and pg_restore into the new dev-Aurora database.
NOTE:  Since the purpose of this load is to provide reasonable amount of data for testing purpose, data load to the postgresql dev database such as GoldenGate was not stopped.
In the situation during the real switch, data load to the source database will be stopped until the switch complete.
A read replica instance is created
(2 read-replicas had been created for our initial testing.  At the end of this initial setup testing, only 1 read-replica is kept for further user testing)
