### ISSUE TITLE
Perform loading tests (Java, Python, Flyway migration, GoldenGate)

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#4287]
### Summary
After initial setup of the new Aurora database, applications that currently used to load the postgresql database need to be tested to make sure data loading/synchronization between source databases and the new Aurora database will still functioning. 

### Related issues
- #4286  
- #4288 
- #4289 
- #4290 
- #4291 

### Completion criteria
The following  application need to be able to routinely perform data loading/synchronization tasks
- [x] Java loading: nightly big tables/aggregation tables loading
- [x] Java loading: flyway migration
- [x] Java loading: efile data loading by Salient
- [x] Python loading: presidential map tables loading
- [x] Python loading: fecmur data loading by Salient
- [x] Golden Gate loading

### Future work
- #4288 
- #4289 
- #4290 
- #4291

**Comment by fecjjeng** [comment]
Currently we are using several different ways to load the postgresql database to keep it in sync with the Oracle data source.  We need to make sure applications that currently used to load the postgresql database also work with the new Aurora database.
Right after the initial data load from pg_restore completed.  We had setup the following to the new aurora database:
- Java loading: nightly big tables/aggregation tables loading
- Golden Gate loading
The above two applications are the one that keep the base tables (and derived fec_fitem_sched tables) in disclosure/staging/fecapp schemas in sync with the Oracle data source.  These had been run successfully.

-  Python loading: presidential map tables loading is used to load presidential map data on demand.  This had been tested using the latest presidential map data refresh from 4/1/2020.  It works successfully.

- flyway migration: This had been initially tested from local mac server by change the flyway configuration file to point to the dev-aurora database instead of the local postgresql database.  
- NOTE: migration file V0191 and V0192 (which are the two latest one and can be re-run without breaking, had beed used to conduct this test by removing them from the flyway_schema_history tables).  This test completed successfully.  
- NOTE: a more formal test had been conducted as part of issue #4288 

- aouser/fecmur data loading by Salient:  Upon our request, Salient had switched the connection to update our postgresql database in DC4 to this new Aurora database at Friday (4/17/2020) evening.  

- real file (real_efile/real_pfile) data loading by Salient:  Upon our request, Salient had switched the connection to update our postgresql database in DC4 to this new Aurora database on Monday 4/20/2020.
