### ISSUE TITLE
Migrate postgresql database instance to new Aurora database instances

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#4297]
### Summary

After initial tests had been successfully performed by database team on the data loading (#4287), this work will serve dual purposes: help testing API and also make sure all data loading process works without issues.  New monitoring scripts will be set up to the new aurora database to set the stage ready for the final switch.  
We plan to do the actual migration/switch tasks on Friday 5/1/2020.  The work are scheduled to be completed on Sunday 5/3/2020.

### Completion criteria
- [x] Start initial setup of dev/stage/prod aurora database to prepare for the switch 
- [x] stop all data loading/refresh process to postgresql databases instances
- [x] export data from current postgresql dev/stage/prod databases instances.
- [x] import data into new Aurora dev/stage/prod database instances
- [x] restart all data loading/refresh process
- [x] connect API server/CircleCI to the new Aurora dev/stage/prod database instances

**Comment by fecjjeng** [comment]
STEP 1:
####################
create Aurora clusers for DEV/STG/PRD
Using teraform
PR #97 (prd) merged
PR #98 (stg) merged
PR #99 (dev) merged


STEP 2:
####################
create database 'fec' in each master instance
drop database 'postgres' in each master instance (postgres is the default database name, easy target for hackers)


STEP 3:
####################
users/roles/permissions
####################
## roles are per postgresql/aurora instance, only need to create once
- create users/roles and permissions as in the current postgresql database instances.
- reset the "utility user account" password to the current postgresql database instances.
- reset individual accunts password upon request. 
(NOTE: some query tool such as pgclient seems to have problem if password has special characters.  DBeaver is ok.  But just don't use special characters in password) 
(NOTE: postgres and Aurora store username in lower case, if not included in double quotes.  Mixed case username is more error prone and will be aviold)


STEP 4:
####################
create an ec2 server in AWS.  Use it to perform the pg_dump and pg_restore work.
On local server, set up ssh key to connect to ec2 server in AWS


STEP 5:
####################
## BEFORE pg_dump, STOP data input into the current Postgresql database
####################
- stop GG jobs to the current database
- Coordinate with Salient to 
	hold data input for Informatica, 
	real file
	fecmur
	aouser
- Hold Informatica nightly process
- comment out cronjobs that runs Oracle package/java programs for big tables change capture/data transfer
- comment out monthly real file cleanup cronjob 
- MV refresh should be already done on Friday morning.  No need to stop.



STEP 6:
####################
## pg_dump
####################
nohup pg_dump -h fec-govcloud-dev.cfojp1ao5rbz.us-gov-west-1.rds.amazonaws.com -v -d fec -U jjeng -j 5 -F d -f /u07/pg-bkup/dev/dev

nohup pg_dump -h fec-govcloud-stage.cfojp1ao5rbz.us-gov-west-1.rds.amazonaws.com -v -d fec -U <username> -j 5 -F d -f /u07/pg-bkup/stage/stage

nohup pg_dump -h fec-govcloud-prod.cfojp1ao5rbz.us-gov-west-1.rds.amazonaws.com -v -d fec -U <username> -j 5 -F d -f /u07/pg-bkup/prod/prod



STEP 7:
####################
## Pre-cleanup job if needed.  Before doing restore
####################


BEFORE restore
####################
## drop GG jobs if there is any connect to the new Aurora database
####################
##(need to stop the replicat, then drop the replicat)
## in ggsci
dblogin sourcedb pgdb_auroradev, USERIDALIAS golden_gate, DOMAIN pgdb_auroradev
stop replicat replicat_name
drop replicat replicat_name



####################
Drop existing fec DB
Create a new fec DB
###################
## need to create another database otherwise can not drop database fec
## in psql
create database my_logindb
\c my_logindb
drop database fec
create database fec


####################
drop replica before import
use default parameter group
####################
## remove replica to speed up the restore
## use default parameter group (the modified one log all transactions, which will generate too much log, also slow down restore)




STEP 8:
####################
Start import with 5 Jobs
####################
## first try to restore use 9 jobs, database crashed and reboot after 3 hours, when indexes creatation on big tables taken places that use too much memory and CPU

####################
pg_restore
## since all objects should be belongs to fec, It is ideal to run pg_restore as user fec
####################
nohup pg_restore /u07/pg-bkup/dev2/dev2 -h dev-aurora.cluster-cfojp1ao5rbz.us-gov-west-1.rds.amazonaws.com -d fec -U fec --role fec -j 5 -v -c

nohup pg_restore /u07/pg-bkup/stage/stage -h stage-aurora.cluster-cfojp1ao5rbz.us-gov-west-1.rds.amazonaws.com -d fec -U fec --role fec -j 5 -v -c

nohup pg_restore /u07/pg-bkup/prod/prod -h prod-aurora.cluster-cfojp1ao5rbz.us-gov-west-1.rds.amazonaws.com -d fec -U fec --role fec -j 5 -v -c


####################
## after import done
####################
## review import logs, make sure error messages are acceptable (trying to drop non-existing objects, mv does not refresh
####################


STEP 9:
####################
## complete refresh of MV 
##	using script for regular refresh, not concurrenly.  It is faster AND refresh concurrently does not work for MV that is populated yet.
####################


STEP 10:
####################
## run analysis of the tables
####################


STEP 11:
####################
## create replica, alter parameter group to allow more logging
####################
- create replica, 
- alter parameter group to allow more logging


STEP 12:
####################
## create or re-hook GG job
####################
dblogin sourcedb pgdb_auroradev, USERIDALIAS golden_gate, DOMAIN pgdb_auroradev


add replicat D2_ADIS, CHECKPOINTTABLE public.checkpointtable, exttrail ./dirdat/efecp/tp EXTSEQNO 2852 EXTRBA 115230755
-- start replicat D2_ADIS
-- status replicat D2_ADIS



add replicat D2_AFAP, CHECKPOINTTABLE public.checkpointtable, exttrail ./dirdat/efecp/tp EXTSEQNO 2852 EXTRBA 115230755
-- start D2_AFAP
-- status D2_AFAP


add replicat D2_ASTG, CHECKPOINTTABLE public.checkpointtable, exttrail ./dirdat/efecp/tp EXTSEQNO 2852 EXTRBA 115230755
-- start replicat D2_ASTG
-- status replicat D2_ASTG


STEP 13:
####################
## point java script to the new Aurora database
####################
point java script to the new Aurora database
start cronjob



STEP 14:
####################
## Hook-up API to the new Aurora database (from cloud foundry) 
####################



STEP 15:
####################
## connect CircleCI
####################
## 	Bastion Host itself does not need to be updated, 
## 	The following two parameter need to be replaced for each environment
## 	(not included here)
####################



STEP 16:
####################
## contact Salient to start all data input work, pointing to the new Aurora database
####################



STEP 17:
####################
## start Informatica Nightly process
####################


STEP 18:
####################
## drop replica instance for postgresql DEV/STG/PRD
####################


STEP 19:
####################
## after one week running without error
## drop mater instance for postresql DEV/STG/PRD 
####################

**Comment by fecjjeng** [comment]
Databases migration completed by database team.  
Followup ticket for tear down opened (#4328).
Close this ticket.
