### ISSUE TITLE
Refactor Elasticsearch management functions

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4399]
**Summary**
In the past, when citations or any entity were missing for a specific AO's or a Case (MUR, ADR, AF) on the website, we run the zero downtime reload command which upload all the legal documents onto elasticsearch service. The Zero downtime task takes ~1.5 hours without causing any downtime on the website and uploads all legal documents. With the regular initialize load commands (for each document type) we anticipate downtime. 

**Things to consider:**
- [ ]  Create a new index (for ex: docs_ao) for AO's only???
- [ ]  Refactor the current code and upload AO documents to the new index on elasticsearch service??? 
- [ ]  Refactor or write a new zero-downtime task to reload AO???

**Completion criteria:**
- [ ] Modify the zero-downtime task to optionally reload a specific document type

**Comment by pkfec** [comment]
Two tasks that we run to upload documents onto elasticsearch service after which the legal documents are available on the website for legal search:

1. Zero downtime - Causes no downtime. Loads all the docs and take ~1.5 hours. 
2. Initialize docs - Its real time process. Causes downtime until each document is uploaded on the elasticsearch service. 

 It appears that we have all of our legal documents uploaded onto one elasticsearch index. After discussing with @fec-jli @lbeaufort we want to create a separate index for each document type and write a zero downtime task for each one of the document type so that we can speed up the  upload documents without causing any downtime on the website.

**Comment by pkfec** [comment]
Un assigning myself as I am not actively working on this issue.
