### ISSUE TITLE
Modify `is_individual` to include intermediaries

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/openFEC#4453]
What we are after:
We need to include contributions from individuals that are categorized as intermediaries (24I and 24T).

Why we are after it:
'IS_INDIVIDUAL' should include all contributions from individuals. 

Related issue(s):
https://github.com/fecgov/FEC/issues/9956

Completion criteria:
- [ ] include 24I and 24T in `is_individual` logic (might be able to use entity_tp = 'IND' to help with this)
- [ ] update SA table
- [ ] update methodology page
- [ ] close https://github.com/fecgov/FEC/issues/9956 once this work is complete

**Comment by PaulClark2** [comment]
We should be able to use `entity_tp` to help us. It looks like we have that information from 2003 to present. We'll need to exclude some transactions that are marked as individuals (entity_tp = 'IND'), because they clearly aren't individuals. 

I"m really bad a regular expressions and we'll need to see if there are other terms we should look from. We might want to include HOUSE but that word can also be a family name. I'm not sure how we deal with that. Here's a sample of the transactions that we should not mark as `is_individual = true`. 

```
select name, entity_tp, transaction_tp, image_num, sub_id 
from DISCLOSURE.F_ITEM_RECEIPT_OR_EXP 
WHERE rpt_yr between 2003 and 2020
AND 
    (  regexp_like (NAME, '(^|\s)ELECT(\s|$)')
    or regexp_like (NAME, '(^|\s)COMMITTEE(\s|$)')
    or regexp_like (NAME, '(^|\s)CONGRESS(\s|$)')
    or regexp_like (NAME, '(^|\s)SENATE(\s|$)')
    or regexp_like (NAME, '(^|\s)FRIENDS(\s|$)')
    or regexp_like (NAME, '(^|\s)PAC(\s|$)'))
and sched_tp_cd = 'SA' 
and transaction_tp in ('24I', '24T') 
and entity_tp = 'IND';
```

**Comment by fecjjeng** [comment]
@PaulClark2 I have some questions on this task:
- The two transaction_cd you want to add to the is_individual (24I and 24T) are for earmarked.
24I	EARMARKED INTERMEDIARY OUT
24T	EARMARKED INTERMEDIARY TREASURY OUT
Should we include them in the is_individual logic for fec_fitem_sched_a tables?

- In the ticket the entity_tp is also mentioned.
Do you mean not simply add 24I and 24T, but only when transaction code are in 24I/24T AND entity_tp = 'IND' then counted them as INDIVIDUAL?  Since entity_tp <> 'IND' only occupy a very small portion of the 24I/24T (24863 out of 17885512 = 0.1%), is it ok to ignore the check of entity_tp in favor of performance?

**Comment by PaulClark2** [comment]
After additional research into the the way `24Is` and `24Ts` are reported by the intended recipient committee, we do not need to modify `is_individual`. These transactions are disclosed and categorized as earmarks (`15Es`) on intended recipient committee's reports. `Is_individual` is capturing these transactions. Adding `24I` and `24T` to `is_individual` would result in double counting these transactions, so closing,. 

See for example: 
`select * from DISCLOSURE.NML_SCHED_A where sub_id = 4082820191130768135;`
`select * from DISCLOSURE.NML_SCHED_A where sub_id = 4091120191672590641;`
