### ISSUE TITLE
Committee totals missing for one committee

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4551]
Reported in the Google group: 

> I came across a joint fundraising committee with receipts and disbursements, but calls to the /committee/{committee_id}/totals/ endpoint return an empty result set for that committee.  I'm curious why that might be.  I couldn't find an existing issue on the committee-totals endpoint that seemed to characterize this.  Here are the specific endpoints I called:
> 
> https://api.open.fec.gov/v1/committee/C00701243/totals/?sort_hide_null=false&api_key=DEMO_KEY&sort=-cycle&sort_null_only=false&per_page=20&sort_nulls_last=false&page=1
> (An empty result set is returned.)
> 
> https://api.open.fec.gov/v1/schedules/schedule_a/?per_page=20&sort_hide_null=false&sort_null_only=false&api_key=DEMO_KEY&committee_id=C00701243&sort=contribution_receipt_date
> (Returns the first set of the 464 receipts records for this committee.)
> 
> https://api.open.fec.gov/v1/schedules/schedule_b/?sort_hide_null=false&sort_null_only=false&per_page=20&api_key=DEMO_KEY&committee_id=C00701243&sort=-disbursement_date
> (Returns the first set of the 77 disbursement records for this committee.)

I confirmed that the committee had activity in 2020, but no data appears on the financial summary page. 
https://www.fec.gov/data/committee/C00701243/?tab=summary

**Completion criteria:**
- [ ] The data displays correctly on the committee's profile page

<img width="918" alt="Screen Shot 2020-08-11 at 11 39 21 AM" src="https://user-images.githubusercontent.com/31420082/89917896-5d638700-dbc7-11ea-83a4-6ce2d334e64f.png">

**Comment by hcaofec** [comment]
"/committee/{committee_id}/totals/" gets data from ofec_totals_house_senate_mv. This mv is based on ofec_totals_combined_mv with filter as 

`(form_type in ['F3', 'F3P', 'F3X') 
  AND (committee_type in ['H', 'S'])
  AND (committee_designation in ['P', 'A']
` 
C00701243 has designation as "Joint fundraising committee" and type "S". Because of the criteria defined above, Joint fundraising committees are not included in ofec_totals_house_senate_mv.

**Comment by hcaofec** [comment]
Another example for Joint fundraising committee: C00700237
