### ISSUE TITLE
Check logs Sprint 13.11 week 1

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4730]
Check logs Sprint 13.11 week 1

Log review needs to be completed for sprint 13.11 week 1 per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

**Comment by hcaofec** [comment]
**FEC-CMS:**
- package.json: 4 ( 1 has been fixed in dev)
    - High: Prototype Pollution https://app.snyk.io/org/fecgov/project/2a97cddb-4b62-4d54-b18f-3b85d55a5e10/#issue-SNYK-JS-DATATABLESNET-1016402, **resolved by fecgov/fec-cms#4272**
    - High: Arbitrary Code Execution (fecgov/fec-cms#4026)
    - High: Regular Expression Denial of Service (ReDoS) fecgov/fec-cms#4266
    - Medium: Prototype Pollution (fecgov/fec-cms#4105)
- requirements.txt: 0

**OPEN-FEC:**
- package.json: 0
- requirements.txt: 0
- data/flyway/build.gradle: 0

**FEC-EREGS:**
- package.json: 0
- requirements.txt: 0

**FEC-PATTERN-LIBRARY:**
- package.json: 0


Cloud.gov Dashboard:
9 deployer accounts, same as last week.

Offboarding:
New ticket fecgov/fec-accounts#333 not in effect until 1/1/21
