### ISSUE TITLE
Check logs Sprint 13.11 week 2

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4731]
Check logs Sprint 13.11 week 2

Log review needs to be completed for sprint 13.11 week 2 per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

- [x] open tickets for Sprint 13.12 week 1 and week 2

**Comment by hcaofec** [comment]
**FEC-CMS:**

- package.json: 4 ( 1 has been fixed in dev)

     - High: Prototype Pollution https://app.snyk.io/org/fecgov/project/2a97cddb-4b62-4d54-b18f-3b85d55a5e10/#issue-SNYK-JS-DATATABLESNET-1016402, resolved by fecgov/fec-cms#4272
     - High: Arbitrary Code Execution (fecgov/fec-cms#4026)
     - High: Regular Expression Denial of Service (ReDoS) fecgov/fec-cms#4266
     - Medium: Prototype Pollution (fecgov/fec-cms#4105)
- requirements.txt: 2 (new)
     - High: Buffer Overflow (fecgov/fec-cms#4307)
     - High: Buffer Overflow ( same as above ticket ) (https://app.snyk.io/vuln/SNYK-PYTHON-PILLOW-1055461)

**OPEN-FEC:**
None

**FEC-EREGS:**
None

**FEC-PATTERN-LIBRARY:**
None

**Search logs:**
User change - Jason Upchurch

Cloud.gov Dashboard:
9 deployer accounts, same as last week.

Offboarding:
fecgov/fec-accounts#333 is closed
