### ISSUE TITLE
Check logs sprint 14.5 - week 2 (04/28)

### ISSUE THREAD

**Issue by rfultz** [fecgov/openFEC#4831]
Log review needs to be completed per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

- [x] open tickets for Sprint 14.6

**Comment by johnnyporkchops** [comment]
**FEC-CMS:**
requirements.txt 1 
 - Med: Cross-site Scripting (XSS) https://github.com/fecgov/fec-cms/issues/4562
 
 package.son: 2
 - High- Underscore Arbitrary Code Execution (due 4/30/21) https://github.com/fecgov/fec-cms/issues/4523
 - Med: lxml Cross-site scripting (XSS): fecgov/fec-cms#4509
 
 **OPEN-FEC:**
package.json: 

  - Med: Regular Expression Denial of Service (ReDoS) https://github.com/fecgov/openFEC/issues/4837

requirements.txt: 
  - High: Deserialization of Untrusted Data (05/28/21) https://github.com/fecgov/openFEC/issues/4836
 
 **FEC-EREGS:**
package.json: None
requirements.txt: None

FEC-PATTERN-LIBRARY:
None

Search logs:
No log results for "user change"

Cloud.gov Dashboard:
9 deployer accounts, same as last week.

Off-boarding:
None since last log check.
