### ISSUE TITLE
Check logs sprint 14.5 - week 1 (04/21)

### ISSUE THREAD

**Issue by rfultz** [fecgov/openFEC#4833]
Log review needs to be completed per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

Last log review : https://github.com/fecgov/openFEC/issues/4824

**Comment by johnnyporkchops** [comment]
**FEC-CMS:**
requirements.txt 1 
 - Medium: Cross-site Scripting (XSS) https://github.com/fecgov/fec-cms/issues/4562
 
 requirements.txt: 1
 - Medium: lxml Cross-site scripting (XSS): fecgov/fec-cms#4509
 
 **OPEN-FEC:**
package.json: None
requirements.txt: 1

 - High: Deserialization of Untrusted Data: #4818 (still no remediation path list)
 
 **FEC-EREGS:**
package.json: None
requirements.txt: 1

FEC-PATTERN-LIBRARY:
None

Search logs:
No log results for "user change"

Cloud.gov Dashboard:
9 deployer accounts, same as last week.

Off-boarding:
None since last log check.
