### ISSUE TITLE
[Snyk: MED] Regular Expression Denial of Service (ReDoS)(06/28/21)

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/openFEC#4837]
Vulnerability in:
openFEC - package.json

### Overview
validator is an A library of string validators and sanitizers.

Affected versions of this package are vulnerable to Regular Expression Denial of Service (ReDoS) via the isEmail function.

**Introduced through:** swagger-tools@0.10.4
**Remediation path:** update to validator@13.6.0

https://app.snyk.io/vuln/SNYK-JS-VALIDATOR-1090602

**Comment by pkfec** [comment]
API currenlty is running on `swagger-tools  v0.10.4`  which was released 3 years ago and there are no updates on this package since 2018.  See here -  https://github.com/apigee-127/swagger-tools/blob/master/RELEASE_NOTES.md#0104-2018-07-20
Cannot update validator to v13.6.0 without upgrading swagger-tool. Reached out to the team for help. 

```
api379) macadmins-mbp-5:openFEC pkasireddy$ npm list validator
openfec@1.0.0 /Users/pkasireddy/Projects/api/openFEC
└─┬ swagger-tools@0.10.4
  └─┬ z-schema@3.25.1
    └── validator@10.11.0
```

**Comment by pkfec** [comment]
`npm list validator` depicts the validator package dependency structure.  The `isEmail` function in validator.js package is not used anywhere in the openFEC repo. After discussing with  @patphongs and @lbeaufort we decided to mark validator.js vulnerability raised by snyk as false positive and ignore the vulnerability.

No additional work is needed. Closing this issue.
