### ISSUE TITLE
Check logs sprint 14 innovation - week 3 (06/02)

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#4859]
Log review needs to be completed per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

- [ ] Make tickets for week 1 and 2 of next sprint.

**Comment by pkfec** [comment]
**FEC-CMS:**
package.json: None

requirements.txt: 2
 - Low: Directory traversal (Django): https://github.com/fecgov/fec-cms/issues/4602
 - High: HTTP Header Injection (Django): https://github.com/fecgov/fec-cms/issues/4622

**OPEN-FEC:**
package.json: 1
 - Med: Regular Expression Denial of Service (ReDoS) https://github.com/fecgov/openFEC/issues/4837

requirements.txt: 1
  - High: Deserialization of Untrusted Data (05/28/21) https://github.com/fecgov/openFEC/issues/4836
 
flyway: None

**FEC-EREGS:**
package.json: None

requirements.txt: 1
 - Low: Django Directory traversal: https://github.com/fecgov/fec-eregs/issues/594
 - High: HTTP Header Injection (Django): https://github.com/fecgov/fec-eregs/issues/600

**FEC-PATTERN-LIBRARY:**
package.json: None

Search logs:
No log results for "user change"

Cloud.gov Dashboard:
9 deployer accounts, same as last week.

Off-boarding:
None since last log check.
