### ISSUE TITLE
Check logs sprint 15.4 - week 2 (07/28) 

### ISSUE THREAD

**Issue by fec-jli** [fecgov/openFEC#4913]
Log review needs to be completed per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

**Related Issue**:  https://github.com/fecgov/openFEC/issues/4912

- [x] Make new tickets for  week 1 and 2 of 15.5 sprint.

**Comment by pkfec** [comment]
FEC-CMS:
package.json: None
requirements.txt: 3
- Medium: wagtail- Cross-site Scripting (https://github.com/fecgov/fec-cms/issues/4723)
- Medium: pillow- Buffer Overflow (https://github.com/fecgov/fec-cms/issues/4753)
- Medium: urllib- Regular Expression Denial of Service (https://github.com/fecgov/fec-cms/issues/4803)

OPEN-FEC:
package.json: None
requirements.txt: 1
- High: Deserialization of Untrusted Data (05/28/21) #4836

flyway: None

FEC-EREGS:
package.json: None
requirements.txt: None

FEC-PATTERN-LIBRARY:
package.json: None

Search logs:
No log results for "user change"

Cloud.gov Dashboard:
9 deployer accounts, same as last week.

Off-boarding:
None since last log check.
