### ISSUE TITLE
Check logs Sprint 17.2 week 1 (02/02/2022)

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#5036]
Log review needs to be completed per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

Ref: [Check logs sprint 17.1 week1](https://github.com/fecgov/openFEC/issues/5019)

**Comment by cnlucas** [comment]
FEC-CMS:
package.json: 1 Medium
[Snyk: Medium]: [node-fetch Information Exposure] (fecgov/fec-cms#5029)

requirements.txt: 0 Critical, 2 Medium, 3 Low
[Snyk:Medium]: django Denial of Service (DoS)
[Snyk:Medium new]: [django Access Restriction Bypass] will solve in fecgov/fec-cms#5030

[Snyk:Low]: [django Directory Traversal]will solve in fecgov/fec-cms#5030
[Snyk:Low]: [django Information Exposure]will solve in fecgov/fec-cms#5030
[Snyk:Low]: [wagtail Information Exposure] will solve in fecgov/fec-cms#5043

*Ignored 3 Medium this week-Upgrading to Pillow 9 would be a risk to us since we are currently on a lower version of Wagtail. Ignored since Pillow is only used within our authenticated CMS system and does not pose an imminent risk closed in* fecgov/fec-cms#5020

OPEN-FEC:
package.json: 1 Medium
[Snyk: Medium]: [User Interface Misrepresentation of Critical Information] (#5007)

requirements.txt: _1 Medium
[Snyk: Medium]: [Celery Stored Command Injection] (#5017)

flyway: 0
_Ignored 1 High, 1 Medium this week because we use the postgresql driver and we are excluding protobuf_ 

FEC-EREGS:
package.json: 0

requirements.txt: 2 Medium, 2 Low
[Snyk: Medium]: [Celery stored command injection] (fecgov/fec-eregs#655)
[Snyk: Medium]: [Access Restriction Bypass] (fecgov/fec-eregs#638)

[Snyk: Low new]: [django Directory Traversal] will solve in fecgov/fec-eregs#638
[Snyk: Low new]: [django Information Exposure] will solve in fecgov/fec-eregs#638

FEC-PATTERN-LIBRARY:
package.json: None

Search logs:
No log results for "User change"

Cloud.gov Dashboard:
9 deployer accounts, same as last week.

Off-boarding:
None for this week
