### ISSUE TITLE
Refactor Tests with Unknown Args 

### ISSUE THREAD

**Issue by cnlucas** [fecgov/openFEC#5487]
### What we’re after

Flask upgrade found a few issues with a few of the tests:  test_candidate_aggregates_by_committee
https://github.com/fecgov/openFEC/pull/5463#discussion_r1254384908

The test is currently passing, but committee_id is an unknown arg. The series of tests in this file should be re-examined and any unknown args removed, and the tests re-written to test the correct filters. 

It might be a good idea to review the other tests that had removed unknown arguments (test_efile_presidential_reports, test_efile_house_senate_reports, test_schedule_a_null_pagination_with_null_sort_column_values_descending, and test_candidate_aggregates_by_committee_full) and see if they need to be re-written. https://github.com/fecgov/openFEC/pull/5463/files

### Related ticket(s)

(Include the tickets that either came before, after, or are happening in tandem with this new ticket)
- [ ] 

### Action item(s)

(These are the smaller tasks that should happen in order to complete this work)
- [ ] 

### Completion criteria

(What does the end state look like - as long as this task(s) is done, this work is complete)
- [ ] 

### References/resources/technical considerations

(Is there sample code or a screenshot you can include to highlight a particular issue? Here is where you reinforce why this work is important)

**Comment by tmpayton** [comment]
I reviewed our automated tests to ensure that we aren't using unknown args in any of them. Most of them were fixed with the Flask upgrade. The only case I found was in `test_candidate_aggregates_by_committee` ( `CommunicationCostByCandidateView` doesn't have a committee field). However since we test the candidate fields in `test_candidate_aggregates_by_committee_full` I don't think this needs to be rewritten since we ignore unknown args by default.
