### ISSUE TITLE
Research ES concurrent_snapshot_execution_exception issue

### ISSUE THREAD

**Issue by cnlucas** [fecgov/openFEC#5535]
### What we’re after
Every few months our ES backups fail on Sundays. The team did some investigation and found the issue might be two-fold: the S3 buckets capacity and that snapshots are being created concurrently which ES does not support. 

We have a ticket to regularly clean out the old snapshots, but this ticket is to make sure we don't have to manually do this every few months and make sure that the snapshots for different indexes are not being created concurrently. 
Discussion in slack: 
https://fecgov.slack.com/archives/C3W9XBBJL/p1691503044668379

### Related ticket(s)

(Include the tickets that either came before, after, or are happening in tandem with this new ticket)
- [ ] 

### Action item(s)

- [x] Confirm the issue with the backups
- [x] Create a plan the will solve the issue long-term
- [ ] Put in a ticket for the work/ Do the work 

### Completion criteria

(What does the end state look like - as long as this task(s) is done, this work is complete)
- [x] We have a plan to fix ES backup issue

**Comment by tmpayton** [comment]
I did research on this issue and confirmed that it is two-fold. 

The first issue that we are having is that we have to manually delete old snapshots. Here are two ways that we could fix this issue:
1. Create a snapshot lifecycle management policy 
    - This solution would take a bit more research to implement. AWS-elasticsearch does not allow the use of X-pack, which would be needed in the python elasticsearch library. To get around the use of X-pack, we would need to find a different way to sign the request. To do this we could try to find another python library, but I haven’t found one that would work yet. 
2. Schedule a celery task to automatically delete old snapshots 

The second issue we are having is that snapshot cannot be created simultaneously with elasticsearch 7.4. In elasticsearch 7.6+ it allows you to create them simultaneously however we can’t upgrade to that version because [cloud.gov](http://cloud.gov/) only supports up to version 7.4. While we wait for the upgrade we can either: 
1. Modify the code to increase sleep time if previous snapshot is still being created 
    - We could query elasticsearch to ensure the previous snapshot is complete by getting the status https://www.elastic.co/guide/en/elasticsearch/reference/7.4/modules-snapshots.html#_snapshot_status
2. Separate the creation of the snapshots into multiple celery tasks and schedule them with enough time apart. 

I think that the best long term solution is to create a celery task that will delete snapshots monthly and to increase the sleep time to ensure that the previous snapshot is complete before creating another one.
