### ISSUE TITLE
Legal search brief outages

### ISSUE THREAD

**Issue by cnlucas** [fecgov/openFEC#5537]
### What we’re after

Legal search often goes up and down very quickly. I've done some investigation, but it warrants a more thorough examination to see if there's anything we can do to prevent it from continuing to happen. I've seen a lot of spam bot activity--which could be the cause. If it is the cause we might want to pair with FE to see what control options we could add to that search box. 

### Related ticket(s)

(Include the tickets that either came before, after, or are happening in tandem with this new ticket)
- [ ] 

### Action item(s)

(These are the smaller tasks that should happen in order to complete this work)
- [x] Determine the cause of the outages
- [x] Create a plan to reduce outages if possible

### Completion criteria

(What does the end state look like - as long as this task(s) is done, this work is complete)
- [ ] 

### References/resources/technical considerations

(Is there sample code or a screenshot you can include to highlight a particular issue? Here is where you reinforce why this work is important)

**Comment by tmpayton** [comment]
My recommendation to reduce outages would be to start by reducing spam. We could do this by implementing a recaptcha on the legal search box. 

[Recaptcha v3](https://developers.google.com/recaptcha/docs/v3) seems like it would be a good fit because it requires no input from the user. Instead Google will send us a score where 1.0 is a good interaction and 0.0 is likely a bot. Then we can set our own thresholds to block certain interactions. 

I checked with FE (@johnnyporkchops) and he mentioned that a recaptcha would be feasible/a good idea. 

If we are still experiencing outages after implementing the recaptcha, I think that the next step would be to look at increasing our elasticsearch [plan](https://cloud.gov/docs/services/aws-elasticsearch/) (we currently have five nodes).

**Comment by tmpayton** [comment]
<img width="1462" height="142" alt="Image" src="https://github.com/user-attachments/assets/9056f59a-8036-45f8-93d6-fadd399902f5" />

<img width="784" height="545" alt="Image" src="https://github.com/user-attachments/assets/50d45b73-65f9-4d17-9daa-1236c68818f4" />

<img width="332" height="50" alt="Image" src="https://github.com/user-attachments/assets/8ba65d64-23dc-484a-b1f2-1b1399ba9bed" />
