### ISSUE TITLE
Research what fields document_highlights are searching

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#5831]
### What we’re after

Keyword search is searching more than just documents. In the [code](https://github.com/fecgov/openFEC/blob/ee4d36e38e4db605ebeeb075a0b1ad204dbba1d2/webservices/resources/legal.py#L166), it is searching for: Highlight searched: "text", "name", "no", "summary", "documents.text", "documents.description". We need to find out what each of these things are so we can better explain to the user.

Maybe we don't need to include no? Are all of the fields relevant? 

### Action item(s)

(These are the smaller tasks that should happen in order to complete this work)

- [x] List out and define all of the searched fields of keyword search

### Completion criteria

(What does the end state look like - as long as this task(s) is done, this work is complete)

- [x] We have the dictionary above

**Comment by tmpayton** [comment]
Here is a list of definitions for all of the searched fields. Some of the definitions differ based on document type. 

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>


<div style='direction:ltr'>


Document type | Text | Name | No | Summary | Documents.text | Documents.description
-- | -- | -- | -- | -- | -- | --
Statutes | Full text of a   section of a statute | Section subheading | Section number of   a statute | N/A | N/A | N/A
MUR | N/A | Primary respondent | MUR number | N/A | Full text from   documents related to a matter under review | Title of the   related document
ADR | N/A | Primary respondent | ADR number | N/A | Full text from   documents related to an alternative dispute resolution | Title of the   related document
AF | N/A | Committee_name | AF number | N/A | Full text from   documents related to an admin fine case | Title of the   related document
Archived MUR | N/A | N/A | MUR number | N/A | Full text of the   archived MUR | N/A
AO | N/A | Requestor | AO number | A short summary of   the advisory opinion subject | Full text from   documents related to the advisory opinion | Title of the   related document



</div>


</body>

</html>

Documents (documents.text and documents.description) refer to all documents related to a case/number. For instance [AO 2024-05](https://www.fec.gov/data/legal/advisory-opinions/2024-05/) has 11 related documents such as final opinion, drafts, and comments. So documents.text refers to the full text from all 11 of those documents and documents.description refers to the titles of those 11 documents. 

I think for now we should keep the `no` field because it is helpful when searching for statute section numbers.

**Comment by JonellaCulmer** [comment]
@tmpayton Do you foresee any issues with us splitting up these up into different search fields rather than having them combined into single fields. For example, for MURS, I'd ideally like to establish a document keywords filter/field that uses document.text and document.description, and rely on the separate fields for MUR number and respondent.

**Comment by tmpayton** [comment]
@JonellaCulmer I don't see any issues with creating a new search/breaking them up. Are you wanting to break up the universal q search? If so, that would probably be a big re-write. Another option could be to create another legal endpoint that's MUR specific while still having the universal search.

**Comment by patphongs** [comment]
@JonellaCulmer @tmpayton A few considerations that I can see us coming across:

- For the `q` universal keyword search, if we only had it search `Documents.text` and `Documents.description`, that would change the way that the global legal search functions as well. It would only be searching legal documents.
- For all the fields we are taking out of the universal keyword search, we need to see if we have another way to search it. For example: AO Summary, MUR respondent, Statutes Name, to name a few. 
- For the new fields or filters we would be creating, we need to figure out how we want them to function. Do we want it to have boolean logic (i.e. exact phrase match)? How would we want it to work?
