### ISSUE TITLE
/election-dates endpoint: for House elections, the election_district property is often an empty string instead of a district

### ISSUE THREAD

**Issue by alexl9412** [fecgov/openFEC#5870]
Providing the House district for House elections is critical for accurately identifying an election. Currently, the election_district property is usually an empty string, except for special elections. For example, below is a primary House election in Arizona where the district is just a string with a space:

            "create_date": "2023-07-06T13:15:36",
            "election_date": "2024-07-30",
            "election_district": " ",
            "election_notes": null,
            "election_party": null,
            "election_state": "AZ",
            "election_type_full": "Primary election",
            "election_type_id": "P",
            "election_year": 2024,
            "office_sought": "S",
            "primary_general_date": "2023-07-06",
            "update_date": "2024-02-14T19:40:03"

**Comment by alexl9412** [comment]
Apologies! Here are some examples of House elections (office_sought = "H") with empty House districts:

            "create_date": "2023-07-06T13:29:27",
            "election_date": "2024-06-25",
            "election_district": " ",
            "election_notes": null,
            "election_party": null,
            "election_state": "CO",
            "election_type_full": "Primary election",
            "election_type_id": "P",
            "election_year": 2024,
            "office_sought": "H",
            "primary_general_date": "2023-07-06",
            "update_date": null

And:

            "create_date": "2023-07-07T10:31:55",
            "election_date": "2024-06-25",
            "election_district": " ",
            "election_notes": null,
            "election_party": null,
            "election_state": "SC",
            "election_type_full": "Primary runoff",
            "election_type_id": "PR",
            "election_year": 2024,
            "office_sought": "H",
            "primary_general_date": "2023-07-07",
            "update_date": null

**Comment by PaulClark2** [comment]
Generally, the election-dates endpoint does not have district information because the election date applies to an entire state. The endpoint only has district information for elections that do not cover an entire state. These election types might have district information: 
ID	 |	Description
----	 |	----
C|	CAUCUS/CONVENTION
R	|RUNOFF
P	|PRIMARY
SG  |SPECIAL GENERAL
SGR  |SPECIAL GENERAL RUNOFF
SPR  |SPECIAL PRIMARY RUNOFF
SC  |	SPECIAL CAUCUS/CONVENTION
SR  |	SPECIAL RUNOFF
SP	|SPECIAL PRIMARY

Here's a list of all election type IDs: 

ID	 |	Description
----	 |	----
G	|	GENERAL
P	|	PRIMARY
R	|	RUNOFF
C	|	CAUCUS/CONVENTION
SG	|	SPECIAL GENERAL
SP	|	SPECIAL PRIMARY
SR	|	SPECIAL RUNOFF
PR	|	PRIMARY RUNOFF
GR	|	GENERAL RUNOFF
SPR	|	SPECIAL PRIMARY RUNOFF
SC	|	SPECIAL CAUCUS/CONVENTION
SGR	|	SPECIAL GENERAL RUNOFF
CAU	|	CAUCUS
CON	|	CONVENTION
