### ISSUE TITLE
Discrepancy between Bulk Data files and committee top-lines

### ISSUE THREAD

**Issue by mchonofsky** [fecgov/openFEC#5911]
### What we’re after

The sum of items in the 'oppexp' bulk data files do not match the operating expenditures in the committee master. Is it possible to get the numbers to match? Not sure if this is exactly the right place for this issue but I hope you can point me in the right direction. Thank you!

### References/resources/technical considerations

For one committee that I have checked:

* https://www.fec.gov/data/committee/C00708552/?cycle=2022 gives total operating expenditures of 654793.09
* The sum of operating expenditures for the file https://www.fec.gov/files/bulk-downloads/2022/oppexp22.zip for that committee is 704028.26

The discrepancy also exists in other cycles, committees, and lines on the committee page. It's not consistently greater than or less than zero.

**Comment by PaulClark2** [comment]
@mchonofsky The operating expenditure file includes memo items. You'll need to exclude these transactions for the total to match what's displayed on the financial summary page of the committee's profile page. See [Form 3X](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3x.pdf#page=7) and its [instructions](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=13) for information about memo items. 

|	MEMO_CD	|	SUM(TRANSACTION_AMT)	|
|	----	|	----	|
|		|	$654,060.84	|
|	X	|	$49,967.42	|

**Comment by mchonofsky** [comment]
@PaulClark2 that's great, very helpful, thank you! Do you know what accounts for the remaining discrepancy? I looked at another example with only a handful of disbursements, where the total was likewise somewhat less than the financial summary value, and I was able to account for every line in the bulk data matching an entry on the disbursements search page. So I'm not sure what the source of the missing value might be. Do I need to parse the .fec files directly?

![image](https://github.com/user-attachments/assets/7fcf702d-627b-4fd3-bb6b-6a8e84dbab76)

**Comment by PaulClark2** [comment]
@mchonofsky the discrepancies you are seeing are because not all the Q2/M7 reports have been processed. The financial summary page is usually updated overnight. If a filing comes in after 7:30 pm, it takes an additional day for the financial summary data to be updated. However, the transaction-level data takes up to 30 days to process with most being processed within 15 days of receipt. 

The operations log endpoint in our openFEC API will allow you to determine if a report's transactions have been processed. 
filings --> /v1/operations-log/

**Comment by mchonofsky** [comment]
Okay, that makes sense, but I'm still a little confused because this is a 2022 report. Are you suggesting that C00708552 has submitted a Q2/M7 report for 2022 recently or included 2022 expenses on its most recent report? As another test case, C00549014 has a Statement of Termination in 2023 but the summary page and the sum of Operational Expenditures don't appear to match either. I hope I'm not missing something obvious and I'm really grateful for your help!

**Comment by PaulClark2** [comment]
I forgot you are looking at 2022 data. I'll look at your specific examples a little later today.

**Comment by PaulClark2** [comment]
@mchonofsky I needed to confirm some operating expenditure reporting requirements. There is no expectation that the sum of the itemized operating expenditure transaction will equal the amount reported on Line 21b of the Detailed Summary Page of a report. 

Expenditures that aggregate to less than $200 in a calendar year to a single vendor are not itemized. So, they will not be in the bulk data file, but the amount will be included in the amount report on Line 21b of the Detailed Summary Page. 

Separate Segregated Funds (SSF) generally do not report operating expenditures because they covered by the connected organization.

**Comment by mchonofsky** [comment]
Got it. Thank you for helping me understand!

**Comment by PaulClark2** [comment]
You're welcome.
