### ISSUE TITLE
Incorrect MUR sort order

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#5982]
### What we’re after

The sort order for MURs seem to be incorrect. This seems to be the case when current MURs end and archived MURs start. Example website link: https://www.fec.gov/data/legal/search/murs/?search=&case_respondents=&case_min_open_date=&case_max_open_date=&case_min_close_date=&case_max_close_date=&offset=3080&limit=20&sort=#results-murs

<img width="702" alt="Screenshot 2024-09-18 at 1 38 16 PM" src="https://github.com/user-attachments/assets/a7d2cd44-86ee-4f8d-a0f0-eed5ca8abdb4">

### Completion criteria

- [ ] MURs and archived MURs are sorted correctly

**Comment by fec-jli** [comment]
Note:
1)The Current MURs are stored in **case_index**, the Arch MURs are stored in **arch_mur_index**
2)Because both MURs are sorted independently when display on the website, the sort order may sometimes be incorrect.
3)So far there are total **7533** MURs(include Arch MURs: 4448 and Current MURs:3085) 
4)Some examples:
ex 1:  case_no= 2804(Arch MUR) -- case_no=2804R(Current MUR)
ex 2: case_no= 3620(Arch MUR) -- case_no=3620(Current MUR)
![Image](https://github.com/user-attachments/assets/812a2cba-5699-45a3-842e-7d66ee101814)

ex 3: (there are 26 Current MUR no with **xxxxR**)
7894R; 4313R

5)will create new view: fecmur.arch_current_mur_sorting_vw to combine both Current MURs and Arch MURs
with integer column 'case_serial' for sorting.
