### ISSUE TITLE
Research data sets for Other entities/Entity Name filter to verify what entity types are being searched

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#6039]
**What we're after:**
Research data sets for Other entities/Entity Name filter to verify what entity types are being searched

**Considerations:**
- Can we split out each entity type for individual filters?
- How clean is the data?
- Are there other categories that we do not know about? 
- Role table - two requestors (redundant?), commenter, counsel/representative   

## Completion Criteria
- [ ] Design is informed of results 
- [ ] Research is documented in this ticket

**Comment by cnlucas** [comment]
Can we split out each entity type for individual filters? We definitely can add filters that search commenter_names  and representative_names like we do for requestor_names. If we add commenter_types and representative_types we could add those filters as well like how our requestor_types filter is working. Current design is to mimic the old system which did not include these types. 
How clean is the data? This is much more clean since we fixed individuals. There will be no more trailing and leading whitespace. The general cleanliness of this data is challenging to determine because there are valid nulls for all categories. 
Are there other categories that we do not know about? 
Entities have role and type– the role table - two requestors (one is redundant), commenter, counsel/representative
The entity types are as follows: 
Federal candidate/candidate committee/officeholder
Publicly funded candidates/committees
Party committee, national
Party committee, state or local
Nonconnected political committee
Separate segregated fund
Labor Organization
Trade Association
Membership Organization, Cooperative, Corporation W/O Capital Stock
Corporation (including LLCs electing corporate status)
Partnership (including LLCs electing partnership status)
Governmental entity
Research/Public Interest/Educational Institution
Law Firm
Individual
Other
