### ISSUE TITLE
Candidate Search sort option 500's

### ISSUE THREAD

**Issue by cnlucas** [fecgov/openFEC#6043]
### What we’re after

We have been having a user hit our candidate search endpoint and try to search by receipts. This passes validation, but is not a feasible option so error's out. 

The call:
https://api.open.fec.gov/v1/candidates/search/?page=1&per_page=20&sort=ways&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false&api_key=DEMO_KEY

In candidates.py line 45
    aliases = {'receipts': models.CandidateSearch.receipts}

### Action item(s)

(These are the smaller tasks that should happen in order to complete this work)

- [ ] Research why this bug is occurring and fix it 
- [ ] Decide to either fix the receipts sorting or remove it from the validation

### Completion criteria

(What does the end state look like - as long as this task(s) is done, this work is complete)

- [ ] Candidate search either works for receipts sorting or will 422

### References/resources/technical considerations

(Is there sample code or a screenshot you can include to highlight a particular issue? Here is where you reinforce why this work is important)

**Comment by fec-jli** [comment]
This url can duplicate the error, (without `q`, with sort=receipts)
http://127.0.0.1:5000/v1/candidates/?page=1&per_page=20&sort=receipts&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

view class: **candidates.py** line 37: **CandidateList**(ApiResource)
model class: **models.Candidate and models.CandidateSearch**

The root cause:
before running select count(*) query, we should validate argument first,

```
        if {'receipts', '-receipts'}.intersection(
            kwargs.get('sort', [])
        ) and 'q' not in kwargs:
            raise exceptions.ApiError(
                'Cannot sort on receipts when parameter "q" is not set',
                status_code=422,
            )

```

This url won't throw error:
http://127.0.0.1:5000/v1/candidates/search/?page=1&per_page=20&sort=ways&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false&api_key=DEMO_KEY
